- hosts: localhost
  gather_facts: yes
  tasks:
    - debug: var=item
      with_multiple:
        - [1, 2, 3, 4, 5]
        - apply: '{"nested_content": [item, "a", "b", "c"]}'
        - with_subelements:
            - items
            - nested_content

    - name: Print default IPs of all hosts in specified groups
      debug: var=item
      with_multiple:
        # First step: get a flat list of all hosts
        # Uses only one group, as that's the only one I know will be available :-)
        - with_flattened: [groups.all]
        # Second step: for each item from previous step, get the ipv4 address
        - apply: hostvars[item].ansible_default_ipv4.address

    - name: Same, but with multiple addresses
      debug: var=item
      with_multiple:
        - with_flattened: [groups.all]
        - apply: hostvars[item].ansible_all_ipv4_addresses + hostvars[item].ansible_all_ipv6_addresses
        # Flatten results of previous step (we want one list of ips, not ips per host)
        - with_flattened: items
